modLoader="javafml"
loaderVersion="[${major_forge},)"
#issueTrackerURL=""
license="LGPL-3.0-or-later"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="isXander"
description='''
${description}
'''
logoFile="icon.png"

[["dependencies.${id}"]]
modId="forge"
mandatory=true
versionRange="[${major_forge},)"
ordering="NONE"
side="BOTH"

[["dependencies.${id}"]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,)"
ordering="NONE"
side="BOTH"

[["dependencies.${id}"]]
modId="yet_another_config_lib"
mandatory=true
versionRange="[2,)"
ordering="NONE"
side="CLIENT"
